services:
  user-service:
    image: maratkk/flow-overstack_user-service:latest
    container_name: user-service
    depends_on:
      - postgres-db
      - keycloak
    ports:
      - "8085:8080"
      - "8086:8081"
    networks:
      - user-service-network
      - flow-overstack_common
    environment:
      ConnectionStrings__PostgresSQL: Server=postgres-db;Port=5432;Database=user-service-db;User Id=postgres; Password=${USERS_DB_PASSWORD}
      Serilog__WriteTo__2__Args__requestUri: http://logstash:8080
      KeycloakSettings__Host: http://keycloak:8080
      KeycloakSettings__AdminToken: ${KC_ADMIN_TOKEN}
      AppStartupSettings__Ports__GrpcPort: 8081
      AppStartupSettings__Ports__RestApiPort: 8080
      AppStartupSettings__Ports__UseHttpsForRestApi: false
      AppStartupSettings__OpenTelemetrySettings__AspireDashboardUrl: http://aspire-dashboard:18889
      AppStartupSettings__OpenTelemetrySettings__JaegerUrl: http://jaeger:4317
      AppStartupSettings__OpenTelemetrySettings__ElasticSearchUrl: http://elasticsearch:9200
      KafkaSettings__Host: broker:29092
  
  
  postgres-db:
    image: postgres:latest
    container_name: postgres-user-db
    ports:
      - "5433:5432"
    networks:
      - pg-network
      - user-service-network
    environment:
      POSTGRES_USER: ${USERS_DB_USER}
      POSTGRES_PASSWORD: ${USERS_DB_PASSWORD}
      POSTGRES_DB: user-service-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8888:80"
    networks:
      - pg-network
      - user-service-network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres-db
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: identity-server
    depends_on:
      - keycloak-db
    networks:
      - user-service-network
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/flowOverStack
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HTTP_ENABLED: true
    command: start
    volumes:
      - keycloak_data:/opt/keycloak/data
  
  keycloak-db:
    image: postgres:latest
    container_name: keycloak-db
    ports:
      - "5434:5432"
    networks:
      - pg-network
      - user-service-network
    environment:
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      POSTGRES_DB: flowOverStack
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data


networks:
  pg-network:
  user-service-network:
  flow-overstack_common:
    external: true
volumes:
  postgres_data:
  keycloak_data:
  keycloak_db_data:
  kafka_data:
  kafka_schema_data:
  elasticsearch-data: