global:
  scrape_interval: 10s
  scrape_timeout: 5s
  evaluation_interval: 10s
scrape_configs:
  - job_name: "user-service"
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [ 'host.docker.internal:7163', 'user-service:8080' ]
  - job_name: "question-service"
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [ 'host.docker.internal:5170', 'question-service:8080' ]