global:
  scrape_interval: 10s
  scrape_timeout: 5s
  evaluation_interval: 10s
scrape_configs:
  - job_name: "UserService"
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [ 'host.docker.internal:7163' ]