using UserService.Domain.Entities;
using UserService.GraphQl.DataLoaders;

namespace UserService.GraphQl.Types;

public class ReputationRuleType : ObjectType<ReputationRule>
{
    protected override void Configure(IObjectTypeDescriptor<ReputationRule> descriptor)
    {
        descriptor.Description("The reputation rule type.");

        descriptor.Field(x => x.Id).Description("The ID of the reputation rule.");
        descriptor.Field(x => x.EventType).Description("The event type this rule reacts to.");
        descriptor.Field(x => x.EntityType).Description("The entity type this rule is associated with.");
        descriptor.Field(x => x.Group).Description("Optional group/category for the rule.");
        descriptor.Field(x => x.ReputationChange).Description("How much reputation this rule changes.");
        descriptor.Field(x => x.ReputationRecords).Description("The reputation records generated by this rule.");

        descriptor.Field(x => x.ReputationRecords)
            .ResolveWith<Resolvers>(x => x.GetReputationRecordsAsync(default!, default!, default!));
    }

    private sealed class Resolvers
    {
        public async Task<IEnumerable<ReputationRecord>> GetReputationRecordsAsync([Parent] ReputationRule rule,
            GroupReputationRuleReputationRecordDataLoader recordLoader, CancellationToken cancellationToken)
        {
            var records = await recordLoader.LoadRequiredAsync(rule.Id, cancellationToken);
            return records;
        }
    }
}