//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserService.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserService.Application.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete default role.
        /// </summary>
        public static string CannotDeleteDefaultRole {
            get {
                return ResourceManager.GetString("CannotDeleteDefaultRole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; contains a null element..
        /// </summary>
        public static string CollectionContainsNullElement {
            get {
                return ResourceManager.GetString("CollectionContainsNullElement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You must specify either &apos;{0}&apos; (optionally with &apos;{1}&apos;), without &apos;{2}&apos; and &apos;{3}&apos;, or &apos;{2}&apos; (optionally with &apos;{3}&apos;), without &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        public static string ConflictingPaginationArguments {
            get {
                return ResourceManager.GetString("ConflictingPaginationArguments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Identity server error.
        /// </summary>
        public static string IdentityServerError {
            get {
                return ResourceManager.GetString("IdentityServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received from cache data is of invalid format.
        /// </summary>
        public static string InvalidCacheDataFormat {
            get {
                return ResourceManager.GetString("InvalidCacheDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a valid base64 string..
        /// </summary>
        public static string InvalidCursorFormat {
            get {
                return ResourceManager.GetString("InvalidCursorFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email is invalid.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be greater than or equal to {1}..
        /// </summary>
        public static string InvalidMinValue {
            get {
                return ResourceManager.GetString("InvalidMinValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Order direction must be a valid enum value..
        /// </summary>
        public static string InvalidOrderDirection {
            get {
                return ResourceManager.GetString("InvalidOrderDirection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pagination parameters are invalid.
        /// </summary>
        public static string InvalidPagination {
            get {
                return ResourceManager.GetString("InvalidPagination", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be between 0 and {1}..
        /// </summary>
        public static string InvalidRange {
            get {
                return ResourceManager.GetString("InvalidRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is invalid.
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Order direction must be specified..
        /// </summary>
        public static string OrderDirectionRequired {
            get {
                return ResourceManager.GetString("OrderDirectionRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Order field must not be empty..
        /// </summary>
        public static string OrderFieldRequired {
            get {
                return ResourceManager.GetString("OrderFieldRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password is wrong.
        /// </summary>
        public static string PasswordIsWrong {
            get {
                return ResourceManager.GetString("PasswordIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation record not found.
        /// </summary>
        public static string ReputationRecordNotFound {
            get {
                return ResourceManager.GetString("ReputationRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation records not found.
        /// </summary>
        public static string ReputationRecordsNotFound {
            get {
                return ResourceManager.GetString("ReputationRecordsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation rule not found.
        /// </summary>
        public static string ReputationRuleNotFound {
            get {
                return ResourceManager.GetString("ReputationRuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation rules not found.
        /// </summary>
        public static string ReputationRulesNotFound {
            get {
                return ResourceManager.GetString("ReputationRulesNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be provided..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must not be empty..
        /// </summary>
        public static string RequiredNonEmpty {
            get {
                return ResourceManager.GetString("RequiredNonEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role already exists.
        /// </summary>
        public static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles not found.
        /// </summary>
        public static string RolesNotFound {
            get {
                return ResourceManager.GetString("RolesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role to be updated is not found.
        /// </summary>
        public static string RoleToBeUpdatedIsNotFound {
            get {
                return ResourceManager.GetString("RoleToBeUpdatedIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role to update is not found.
        /// </summary>
        public static string RoleToUpdateIsNotFound {
            get {
                return ResourceManager.GetString("RoleToUpdateIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User alredy exists.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has this role.
        /// </summary>
        public static string UserAlreadyHasThisRole {
            get {
                return ResourceManager.GetString("UserAlreadyHasThisRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already taken.
        /// </summary>
        public static string UsernameAlreadyTaken {
            get {
                return ResourceManager.GetString("UsernameAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users not found.
        /// </summary>
        public static string UsersNotFound {
            get {
                return ResourceManager.GetString("UsersNotFound", resourceCulture);
            }
        }
    }
}
