name: Qodana
on:
  workflow_call:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: Download Unit Test Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-unit
          path: coverage
      - name: Download Functional Test Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-functional
          path: coverage
      - name: ls
        run: |
          ls
          ls coverage
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.1
        with:
          pr-mode: false
          args: >
            -i,.,                                
            --coverage-dir,coverage,
            --linter,jetbrains/qodana-dotnet:2025.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_ENDPOINT: 'https://qodana.cloud'