name: Qodana
on:
  workflow_call:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: Set up .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: '9.0'
      - name: Download Unit Test Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-unit
          path: coverage
      - name: Download Functional Test Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-functional
          path: coverage
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
      - name: Merge coverage reports
        run: |
          mkdir -p .qodana/code-coverage
          reportgenerator \
            -reports:coverage/*.xml \
            -targetdir:.qodana/code-coverage \
            -reporttypes:opencover \
            -reportfile:merged
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.1
        with:
          pr-mode: false
          args: >
            -i,.,                                
            --coverage-dir,.qodana/code-coverage,
            --linter,jetbrains/qodana-dotnet:2025.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_ENDPOINT: 'https://qodana.cloud'